version: "3.1"

services:
  db:
      image: mysql
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./init:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: bookish
        MYSQL_ROOT_PASSWORD: 123pass
