// Code generated by MockGen. DO NOT EDIT.
// Source: ./renter.go

// Package renter is a generated GoMock package.
package renter

import (
	bookish_server "github.com/davidlick/bookish/bookish-server"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// ListAll mocks base method
func (m *MockStorage) ListAll() ([]bookish_server.Renter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]bookish_server.Renter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll
func (mr *MockStorageMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockStorage)(nil).ListAll))
}

// FetchDetails mocks base method
func (m *MockStorage) FetchDetails(id int) (bookish_server.Renter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDetails", id)
	ret0, _ := ret[0].(bookish_server.Renter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDetails indicates an expected call of FetchDetails
func (mr *MockStorageMockRecorder) FetchDetails(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDetails", reflect.TypeOf((*MockStorage)(nil).FetchDetails), id)
}

// New mocks base method
func (m *MockStorage) New(name, address, email, phoneNumber string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", name, address, email, phoneNumber)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New
func (mr *MockStorageMockRecorder) New(name, address, email, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockStorage)(nil).New), name, address, email, phoneNumber)
}
